[project]
name = "rco-cli"
version = "0.1.0"
description = "CLI for RendacomOpcoes"
requires-python = ">=3.9"
dependencies = [
  "typer[all]",
  "requests",
  "python-dotenv",
  "urllib3<2.0"         
]

[project.scripts]
rco = "rco.cli:app"
